### ISSUE TITLE
how to start?

### ISSUE THREAD

**Issue by onthetunnel** [haardikk21/binance-trader-csharp#1]
Hello Dear, i am noob for coding can you teach me how to use it ?
and can i know this binance-trader-csharp can auto tracking all symbol/coins on binance(i.means auto track all coin on binance on same time) and auto place order for upper trend coins ? Thanks You!

**Comment by haardikk21** [comment]
@onthetunnel - This is an experimental project and not meant for practical use. Please don't actually use this software unless you want to potentially lose all your money.

**Comment by onthetunnel** [comment]
Dear Haardikk21 , Thanks for let me knowing , but can i testing it please ? Thanks You !

**Comment by haardikk21** [comment]
A `config.json` is provided with basic options you need to fill out. You can build the solution in Visual Studio or something similar to get an executable for it.

**Comment by onthetunnel** [comment]
Dear , Thabks For teaching but can i add multiple coin(symbol) and auto trade multiple coin ?

**Comment by haardikk21** [comment]
@onthetunnel No not with this software. This is not meant for that or even meant to be a practical trading application. Don't use this with actual money.

**Comment by onthetunnel** [comment]
i just testing , hope you can teach me how to config it for tracking all or multiple symbols , Thanks !
